{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    _7zz
    bind
    docker-buildx
    docker-compose
    dust
    exiftool
    ffmpeg
    gcc
    gdb
    go
    htop
    jq
    mariadb
    mediainfo
    netcat
    nmap
    nodejs
    openvpn
    picocom
    python3
    python3Packages.beautifulsoup4
    python3Packages.flask
    python3Packages.ipykernel
    python3Packages.networkx
    python3Packages.numpy
    python3Packages.openpyxl
    python3Packages.pip
    python3Packages.pipx
    python3Packages.pwntools
    python3Packages.pycryptodome
    python3Packages.pymongo
    python3Packages.regex
    python3Packages.scikit-learn
    python3Packages.seaborn
    python3Packages.sympy
    python3Packages.z3-solver
    ripgrep-all
    rustup
    scc
    smartmontools
    sshpass
    sshuttle
    strace
    sysstat
    tcpdump
    testdisk
    timewarrior
    traceroute
    unzip
    valgrind
    wget
    which
    wireguard-tools
    xclip
    xdg-utils
    zip
  ];
}
