{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    _7zz
    bind
    docker-buildx
    docker-compose
    omp
    ffmpeg
    gcc
    gdb
    go
    htop
    jq
    mediainfo
    netcat
    nmap
    openvpn
    python3
    python3Packages.beautifulsoup4
    python3Packages.flask
    python3Packages.ipykernel
    python3Packages.networkx
    python3Packages.numpy
    python3Packages.openpyxl
    python3Packages.pip
    python3Packages.pymongo
    python3Packages.regex
    python3Packages.scikit-learn
    python3Packages.seaborn
    python3Packages.sympy
    ripgrep-all
    rustup
    scc
    smartmontools
    sshpass
    sshuttle
    strace
    sysstat
    tcpdump
    testdisk
    timewarrior
    traceroute
    unzip
    valgrind
    wget
    which
    wireguard-tools
    xclip
    xdg-utils
    mpv
    zip
    android-tools
    usbutils
    wireshark
  ];
}
